### ISSUE TITLE
ext:form error

### ISSUE THREAD

**Issue by kersten** [andersundsehr/aus_driver_amazon_s3#10]
Hi,

didn't self check yet, but if i tell the ext:form that forms are found on S3 I get following error:

Error executing "GetObjectAcl" on "https://s3.eu-central-1.amazonaws.com/XXX/formulare/?acl"; AWS HTTP error: Client error: `GET https://s3.eu-central-1.amazonaws.com/XXX/formulare/?acl` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...) NoSuchKey (client): The specified key does not exist. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>formulare/</Key><RequestId>XXX</RequestId><HostId>XXX</HostId></Error> 

Would you mind to check this?

**Comment by Lagerregal** [comment]
Hey, which TYPO3 version have you tried? Current TYPO3 8.7? The new "form" or the old "form_legacy" extension? Does this error still occur?

**Comment by kersten** [comment]
8.7 with the new form plugin. Didn't test again yet. Will try out.

**Comment by kersten** [comment]
@Lagerregal looks like it is running, thanks :)
