### ISSUE TITLE
Add AWS Europe (Milan) Region

### ISSUE THREAD

**Issue by gregordonsky** [andersundsehr/aus_driver_amazon_s3#103]
The AWS Europe (Milan) Region is not included in [[AmazonS3DriverFlexForm.xml](https://github.com/andersundsehr/aus_driver_amazon_s3/blob/master/Configuration/FlexForm/AmazonS3DriverFlexForm.xml)]

Region Name | Website Endpoint | Route 53 Hosted Zone ID
-- | -- | --
Europe (Milan) | s3-website.eu-south-1.amazonaws.com | Z30OZKI7KPW7MI

**Comment by Lagerregal** [comment]
Thanks for your contribution! 
Fixed with #106
