### ISSUE TITLE
Legacy Ter release packages wrong guzzlehttp for Typo3 V11

### ISSUE THREAD

**Issue by Xarno** [andersundsehr/aus_driver_amazon_s3#110]
The dependent aws-sdk has this dependency:
[guzzlehttp/guzzle]: ^6.5.8 || ^7.4.5

But typo3/cms-core V11 needs 
[guzzlehttp/guzzle]: ^7.4.5

In the Ter release version 6.5.8 is included, which does not work with Typo3 11 and leading to: 
Call to undefined method GuzzleHttp\Utils::chooseHandler()

**Comment by jblnw** [comment]
I do have the same problem. I want to use this extension with Typo3 11.

**Comment by Xarno** [comment]
@jblnw What works is to convert your typo3 to be composer based.

**Comment by SirRuddy** [comment]
Got the same issue. Are you working on a solution without composer?

**Comment by jblnw** [comment]
Converting my Typo3 installation to composer mode worked well for me.
