### ISSUE TITLE
TYPO3 12 Support

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [andersundsehr/aus_driver_amazon_s3#132]
We are working on a TYPO3 v12 Site right now and considering this extension. Is there anything in the making already or the possibility to sponser and support the development of a TYPO3 v12 ready version?

**Comment by andreasisaak** [comment]
I feel the same way about the projects I work on. I also need the extension and am interested in supporting you in the development and release of v12. If there's fundraising or something, please get in touch.
