### ISSUE TITLE
FileMount not visible in V12 for BE-Users

### ISSUE THREAD

**Issue by koch-louis** [andersundsehr/aus_driver_amazon_s3#138]
We are experiencing issues with the permission assignment of the FileMount in V12. 
Specifically, the S3 Filemount does not appear in the Filelist for BE-Users despite proper permission configuration. 
However, admins can see it.

TYPO3: 12.4.9
aus-driver-amazon-s3: dev-master#a3747168313024f88476110c86eed66171864051

**Comment by weakbit** [comment]
Hi @koch-louis 
Did you create the proper filemount?

I tried to reproduce creating a filemount named test
![create-filemount](https://github.com/andersundsehr/aus_driver_amazon_s3/assets/12049749/6e312c5c-5372-40dc-b352-0717502c5e2a)

After adding that to the Backend Users Filemounts, swithing to the User just shos up the Filemount
![resulting-filemount](https://github.com/andersundsehr/aus_driver_amazon_s3/assets/12049749/82fa3cf7-3b15-4898-8428-bcde4e668afc)

You can also try to use the current dev-master, if i've overseen a fix which was done in meanwhile.

**Comment by koch-louis** [comment]
We found the error.
It was related to an extension on our site.
Sorry for the inconvenience.
