### ISSUE TITLE
Error executing "GetObjectAcl" on "https://s3.eu-central-1.amazonaws.com

### ISSUE THREAD

**Issue by boardcaptain** [andersundsehr/aus_driver_amazon_s3#23]
Hi at all,
we got AWSHTTP erros in the filelist Modul. Could you please give us a hint?
the storage is mounted in typo3 and  list objects, but pointed out this message below
thnx torsten
ext version 1.5.5
TYPO3 7.6.23 on windows server 2008 iis with php 7.1.10
	
Error executing "GetObjectAcl" on "https://s3.eu-central-1.amazonaws.com/xxxxxxxx/%5C/?acl"; AWS HTTP error: Client error: `GET https://s3.eu-central-1.amazonaws.com/xxxxxxxxx/%5C/?acl` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message> (truncated...) NoSuchKey (client): The specified key does not exist. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>\/</Key><RequestId>7C403A73D99D56BA</RequestId><HostId>xxxxxxxxxxx+xxxxxxxxxxxxxxxx=</HostId></Error>

**Comment by Lagerregal** [comment]
Hey, thanks for your report.
- Does this issue still exists with the current master? (Composer: "dev-master")
- Can you please check your TYPO3 FAL tables for invalid entries?
- Maybe it's an issue with Windows - This is extension is not tested with Windows Servers, but I think it should work

**Comment by boardcaptain** [comment]
Hi Markus, we will check it asap und give feedback. Thnx for your quick reply.  :-)

**Comment by Lagerregal** [comment]
Closed because TYPO3 7.6 is not supported anymore
