### ISSUE TITLE
ImageProcessing

### ISSUE THREAD

**Issue by kersten** [andersundsehr/aus_driver_amazon_s3#27]
I created this issue two years ago and found it now, because the error still exists:

https://forge.typo3.org/issues/70886

Could you help me getting this to work?

**Comment by Lagerregal** [comment]
Hey, thanks for your report. How do you use the VHS v:media.image view helper?
What is the content of `{settings.logo}` in 
`<v:media.image src="{settings.logo}" srcset="480,768,992,1200" alt="Test" />`?

**Comment by Lagerregal** [comment]
Hey, I analysed this issue: 
This VHS <v:media.picture> ViewHelper is not compatible with external FAL drivers like AWS.

This missing VHS feature is tracked here: FluidTYPO3/vhs#1439
