### ISSUE TITLE
Video Mimetype (youtube, vimeo) is detected wrong

### ISSUE THREAD

**Issue by onigunn** [andersundsehr/aus_driver_amazon_s3#34]
**Requirements**
* no local filestorage available
* min. 1 S3 storage is configured
* TYPO3 8.7 lts (should be the same in 7.6 lts)

**Steps**
* Create Text & Media element
* Use inline "Add media by url" - (same behavior on adding video "files" by using fileadmin)

**Result**
You will see an inline element of type Image.

**Investigation**
Problem is settled in` \AUS\AusDriverAmazonS3\Driver\AmazonS3Driver::getMetaInfoFromResponse `and the way driver is detecting mime types on files. File meta content is collected by calling the S3 client `headObject` method. Technically this is not wrong but business logic wise. TYPO3 video "files" are simply JSON files with some metadata. So S3 detects `.youtube/.vimeo` file as `plain/text` which causes` \TYPO3\CMS\Core\Resource\Index\Indexer` to assume on` \TYPO3\CMS\Core\Resource\Index\Indexer::getFileType` the given file is a text file. By "weird" behavior of backend renderer the inline element shows up as image reference, but this is not related with the S3 driver.

I guess easiest way to handle TYPO3 business logic cases related to files would be to rely for file information tasks to `\TYPO3\CMS\Core\Type\File\FileInfo`.

**Comment by p-schlosser** [comment]
Hello there.
Is there any workaround for this issue? 
I add custom fields to files only of type video. So if the file is stored in S3 storage I can't access the custom field.
