### ISSUE TITLE
cant delete files anymore after update to typo3 8.7.16

### ISSUE THREAD

**Issue by dni** [andersundsehr/aus_driver_amazon_s3#36]
seems like something in TYPO3 changed, which results in a stuck when trying to delete a file.
may have something todo with this https://review.typo3.org/#/c/57052/.
anyone with a similar issue?

**Comment by dni** [comment]
Fatal error: Maximum execution time of 240 seconds exceeded in /var/www/dummy/typo3conf/ext/aus_driver_amazon_s3/Classes/Driver/AmazonS3Driver.php on line 1418

**Comment by dni** [comment]
line 1418 doesnt seem to be the issue the first time, because if i die after 1418 it get hit instant.

**Comment by dni** [comment]
OK renaming is working is subdirectoriy not on the root directory.

**Comment by dni** [comment]
i tested it again with 8.7.15, its a 8.7.16 exclusive behaviour!

**Comment by dni** [comment]
using this file from 8.7.15 instead of the file from 8.7.16 fixes the errors.

typo3/sysext/core/Classes/Resource/ResourceStorage.php

**Comment by dni** [comment]
ok i think i found it, it my opinion its a core bug, ill submit a issue and a fix for it, and the error should be done, when deleting, still found no solution for why the rename on the root folder isnt working.

**Comment by dni** [comment]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1329647780: Object with identifier "2:" does not exist in storage | TYPO3\CMS\Core\Resource\Exception\ResourceDoesNotExistException thrown in file /srv/typo3_src-8.7.15/typo3/sysext/core/Classes/Resource/ResourceFactory.php in line 565. Requested URL: /typo3/index.php?ajaxID=%2Fajax%2Ffile%2Fexists&ajaxToken=--AnonymizedToken--&fileName=__RG_074404444_1.PDF&fileTarget=2%3A&_=1528805716265 


seems like the fileTarget= isnt posted correctly

**Comment by dni** [comment]
<input name="file[rename][0][destination]" value="2:" type="hidden">
should be 
<input name="file[rename][0][destination]" value="2:/" type="hidden">

for the root-directory, starting to think this is also a corebug

**Comment by dni** [comment]
ok changing this function in the driver solves the problem, and the next typo3 update it will be fixed too.
```
/**
    * @param string &$identifier
    */
   protected function normalizeIdentifier(&$identifier)
   {
       $identifier = str_replace('//', '/', $identifier);
       if ($identifier !== '/') {
           $identifier = ltrim($identifier, '/');
       }
   }
```

**Comment by BastianBalthasarBux** [comment]
Can confirm issue and solution by changing normalizeIdentifier in class Driver.

**Comment by Lagerregal** [comment]
Fixed with this commit (Jun 13, 2018): https://github.com/andersundsehr/aus_driver_amazon_s3/commit/2843147b1df1bb749611649f8196bf9680a7edab
