### ISSUE TITLE
Fatal errors with aus_driver_amazon_s3 and TYPO3 8.7

### ISSUE THREAD

**Issue by smittna** [andersundsehr/aus_driver_amazon_s3#40]
Hello,

we have problems with the extension (tested latest 1.7.1 and an older 1.6.0) and TYPO3 (8.7.17)
First (already reported #35):
Fatal error: Cannot redeclare GuzzleHttp\json_encode() (previously declared in /typo3_src-8.7.17/vendor/guzzlehttp/guzzle/src/functions.php:322)

quick fix: removing all GuzzleHttp-things in aws-autoloader.php Is this a solution?

Second (when selecting the file list view):
Fatal error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the ListObjectsV2 operation: [Bucket] is missing and is a required parameter in ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/Api/Validator.php:65
Stack trace: #0 ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/Middleware.php(78): Aws\Api\Validator->validate('ListObjectsV2', Object(Aws\Api\StructureShape), Array) #1 ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/S3/S3Client.php(425): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL) #2 ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/S3/S3Client.php(448): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL) #3 ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/S3/S3Client.php(38 in ./typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/Aws/Api/Validator.php on line 65

With TYPO3 7.6 and same configuration no problem.

**Comment by Lagerregal** [comment]
Does this error occurs on a composer based setup?
Please use composer to install this extension (highly recommended).

**Comment by Lagerregal** [comment]
Duplicated by #35
