### ISSUE TITLE
Deleting folder recursively not using the subfolder identifier

### ISSUE THREAD

**Issue by lsiemon** [andersundsehr/aus_driver_amazon_s3#43]
` 
if ($subFolder) {
$this->deleteFolder($subFolder, $deleteRecursively);
}
`

should be 

` if ($subFolder) {
                             $this->deleteFolder($subFolder->getIdentifier(), $deleteRecursively);
                        }`

https://github.com/andersundsehr/aus_driver_amazon_s3/blob/e14821dcf73bb7abc352b120a0d1a194b5e4bc96/Classes/Driver/AmazonS3Driver.php#L471

**Comment by Lagerregal** [comment]
How can I reproduce this error?

**Comment by Lagerregal** [comment]
Issue was closed because there was no response after a while.
