### ISSUE TITLE
Fatal Error in 9.5.1

### ISSUE THREAD

**Issue by melliks** [andersundsehr/aus_driver_amazon_s3#46]
Fatal error: Cannot redeclare GuzzleHttp\uri_template() (previously declared in typo3conf\ext\aus_driver_amazon_s3\Resources\Private\PHP\Aws\GuzzleHttp\functions.php on line 31

**Comment by georgringer** [comment]
I guess related to #40 by reading

**Comment by toco3** [comment]
Same here with TYPO3 8.7.20 and PHP 7.1

I could solve it by commenting some lines out in aus_driver_amazon_s3/Resources/Private/PHP/Aws/aws-autoloader.php

I got 3 errors 

**Fatal error: Cannot redeclare GuzzleHttp\json_encode() (previously declared in /typo3cms/typo3_src-8.7.20/vendor/guzzlehttp/guzzle/src/functions.php:322) in /typo3cms/com.toco3/typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/GuzzleHttp/functions.php on line 323**
892 #'GuzzleHttp\functions' => __DIR__ . '/GuzzleHttp/functions.php',
924 #require __DIR__ . '/GuzzleHttp/functions.php';


**Fatal error: Cannot redeclare GuzzleHttp\Psr7\_caseless_remove() (previously declared in /typo3cms/typo3_src-8.7.20/vendor/guzzlehttp/psr7/src/functions.php:813) in /typo3cms/com.toco3/typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/GuzzleHttp/Psr7/functions.php on line 813**
878 #'GuzzleHttp\Psr7\functions' => __DIR__ . '/GuzzleHttp/Psr7/functions.php',
925 #require __DIR__ . '/GuzzleHttp/Psr7/functions.php';


**Fatal error: Cannot redeclare GuzzleHttp\Promise\coroutine() (previously declared in /typo3cms/typo3_src-8.7.20/vendor/guzzlehttp/promises/src/functions.php:454) in /typo3cms/com.toco3/typo3conf/ext/aus_driver_amazon_s3/Resources/Private/PHP/Aws/GuzzleHttp/Promise/functions.php on line 454**
833 #'GuzzleHttp\Promise\functions' => __DIR__ . '/GuzzleHttp/Promise/functions.php',
926 #require __DIR__ . '/GuzzleHttp/Promise/functions.php';

After I commented out these six lines the errors have gone and up to now I could not detect any side issues...

**Comment by Lagerregal** [comment]
Should be resolved with #74
