### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by aminemeister** [andersundsehr/aus_driver_amazon_s3#48]
Hello!
we got a random error message like:
#0 /app/vendor/aws/aws-sdk-php/src/Middleware.php(78): Aws\Api\Validator->validate('HeadObject', Object(Aws\Api\StructureShape), Array)
#1 /app/vendor/aws/aws-sdk-php/src/S3/S3Client.php(447): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /app/vendor/aws/aws-sdk-php/src/S3/S3Client.php(470): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#3 /app/vendor/aws/aws-sdk-php/src/S3/S3Client.php(404): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#4 /app/vendor/aws/aws-sdk-php/src/S3/S3Client.php(423): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#5 /app/vendor/aws/aws-sdk-php/src/Middleware.php(54): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#6 /app/vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#7 /app/vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): Aws\S3\SSECMiddleware->__invoke(Object(Aws\Command), NULL)
#8 /app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(64): Aws\IdempotencyTokenMiddleware->__invoke(Object(Aws\Command))
#9 /app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): Aws\AwsClient->executeAsync(Object(Aws\Command))
#10 /app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(77): Aws\AwsClient->execute(Object(Aws\Command))
#11 /app/web/typo3conf/ext/aus_driver_amazon_s3/Classes/Driver/AmazonS3Driver.php(1107): Aws\AwsClient->__call('headObject', Array)
#12 /app/web/typo3conf/ext/aus_driver_amazon_s3/Classes/Driver/AmazonS3Driver.php(1091): AUS\AusDriverAmazonS3\Driver\AmazonS3Driver->getMetaInfo('')
#13 /app/web/typo3conf/ext/aus_driver_amazon_s3/Classes/Driver/AmazonS3Driver.php(293): AUS\AusDriverAmazonS3\Driver\AmazonS3Driver->objectExists('')

**Comment by Lagerregal** [comment]
Should be fixed with #50
