### ISSUE TITLE
Out of memory error when uploading large files

### ISSUE THREAD

**Issue by kellerrennkadse** [andersundsehr/aus_driver_amazon_s3#61]
When uploading files that are larger than the php memory limit, the extension triggers an out of memory error, due to this line:

https://github.com/andersundsehr/aus_driver_amazon_s3/blob/master/Classes/Driver/AmazonS3Driver.php#L383

`file_get_contents` loads the full file into memory, hence exceeding the memory limit.

An alternative would be using the Multipart Uploader integrated into the AWS PHP SDK
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html

**Comment by Lagerregal** [comment]
Thanks for this request! It's solved with the latest version https://github.com/andersundsehr/aus_driver_amazon_s3/commit/7ab21e24d78df524ce4f7b2291f0858984353594
