### ISSUE TITLE
Success Message everywhere

### ISSUE THREAD

**Issue by dni** [andersundsehr/aus_driver_amazon_s3#7]
Hi, got the extension from the TER and there are Success Messages everywhere, see Screenshot
![bildschirmfoto 2017-03-23 um 17 14 33](https://cloud.githubusercontent.com/assets/1743657/24257908/663772b0-0fec-11e7-880e-ffd99fe414e4.png)

Maybe better would be only showing after saving the storage, i think this was previous behaviour, only seeing this messages since some versions.

**Comment by Lagerregal** [comment]
Hi, which TER version do you use? 

P.S. We recommend to install the extension via Composer / Packagist https://packagist.org/packages/andersundsehr/aus-driver-amazon-s3

**Comment by dni** [comment]
where do i see me ter version? im using typo3 7.6.16

**Comment by Lagerregal** [comment]
You can see the version in the extension manager. Please update to the latest version.

**Comment by dni** [comment]
ok issue is now gone ;) i updated, ty

**Comment by dni** [comment]
wow, now also the filelist and the backend are much faster also ;) nice
