### ISSUE TITLE
Problem with dependecy aws/aws-sdk-php 3.147.5 

### ISSUE THREAD

**Issue by tomasnorre** [andersundsehr/aus_driver_amazon_s3#76]
The aws/aws-sdk-php version 3.147.5 breaks the Backend editing of the aus_driver_amazon_s3. I don't know why haven't looked into it. I have tested from 3.146.0->3.147.5 and only the 3.147.5 breaks the editing. 

Steps to reproduce: 

1. Create a new File storage
2. Select "Amazon S3" as driver
3. Press "ok" to accept the required refresh.

The error I'm getting is: 
```
Uncaught TYPO3 Exception
Region must be a valid RFC host label.

Aws\Exception\InvalidRegionException thrown in file
/htdocs/Packages/Libraries/aws/aws-sdk-php/src/ClientResolver.php in line 543.

32 Aws\ClientResolver::_apply_endpoint_provider(Aws\Endpoint\Partition, array, Aws\HandlerList)


/htdocs/Packages/Libraries/aws/aws-sdk-php/src/ClientResolver.php:

00321:             is_valid:
00322:             if (isset($a['fn'])) {

00323:                 $a['fn']($args[$key], $args, $list);

00324:             }
```

I have "fixed" this locally for now, by requiring a 3.147.4 version instead.

**Comment by w0nk1** [comment]
This issue is still occuring, any plans to fix that? So it would not work out of the box.
