### ISSUE TITLE
Image Preview in TYPO3 Backend

### ISSUE THREAD

**Issue by nilsweichler** [andersundsehr/aus_driver_amazon_s3#90]
Hi everyone,

after setting everything up my TYPO3 gets connected to my IONOS S3 Bucket.
Everything works for the Front End but in my TYPO3 Backend images on the S3 are not getting loaded.

I've inspected the not loading images and the src of an image was like:
`https://s3.stage.***.de/https:/***.s3-de-central.profitbricks.com/_processed_/f/6/***.jpg`

I blurred out some parts with ***

Could that be a configuration problem? Or do I have to configure something somewhere else?

My config:
Bucket: mybucketname
Custom host name: https://s3-de-central.profitbricks.com
AWS S3: Public base URL (optional): mybucketname.s3-de-central.profitbricks.com
Cache header: max age (in seconds, optional): 0
Protocol: auto
Signature: auto
Case sensitive file system? Yes

**Comment by cweiske** [comment]
Try to add a slash to the public base URL.

In my development notes I have an entry that sounds similar:

> Vorschau-Bilder fixen
> - Konfiguration:
> `publicBaseUrl = files.foo.local:9062/foo-typo3/`



</div></li></ul>

**Comment by nilsweichler** [comment]
The bucket name contained underscores, so Typo3 did not recognize it as a subdomain.
